import { jsPDF } from "jspdf";
import "jspdf-autotable";

export const downloadResultsPDF = (role: string, results: any[]) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(22);
  doc.text(`${role} - Mastery Report`, 20, 20);
  doc.setFontSize(12);
  doc.text(`Generated by InterVexia AI on ${new Date().toLocaleDateString()}`, 20, 30);

  // Table Data
  const tableRows = results.map((q, index) => [
    index + 1,
    q.question,
    q.userAnswer,
    q.correctAnswer,
    q.isCorrect ? "✅" : "❌"
  ]);

  (doc as any).autoTable({
    startY: 40,
    head: [['#', 'Question', 'Your Answer', 'Correct Answer', 'Status']],
    body: tableRows,
    theme: 'grid',
    headStyles: { fillStyle: [37, 99, 235] } // InterVexia Blue
  });

  doc.save(`${role}_InterVexia_Report.pdf`);
};